name: publish-tagging

on:
  push:
    tags:
    - 'v*'
jobs:
  build_npm_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: actions/setup-node@master
      with:
        node-version: 14.0

    - name: install dependencies
      run: |
        npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

    - name: build dist
      run: |
        npm run build-dist

    - name: publish dist
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      run: |
        npm publish
