name: publish-tagging

on:
  push:
    tags:
    - 'v*'
jobs:
  build_npm_package:
    runs-on:ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: actions/setup-node@master
      with:
        node-version: 14.0

    - name: install dependencies
      run: |
        npm install

    - name: build electron to dist
      run: |
        npm run build-dist

    - name: publish electron to dist
      with:
        registry-url: https://npm.pkg.github.com/flintdev
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      run: |
        npm publish
